<?php
/**
 * Translation
 *
 * If translation is not found, then 'en' is tried next.
 *
 * If no english translation found, then "<key>[<lang>]" string is used.
 */
return [
    // index from csv
    'amber' => ['en' => 'Amber'],
    'seed' => ['en' => 'Seed'],
    'fiber' => ['en' => 'Fiber'],
    'bark' => ['en' => 'Bark'],
    'sap' => ['en' => 'Sap'],
    'resin' => ['en' => 'Resin'],
    'oil' => ['en' => 'Oil'],
    'shell' => ['en' => 'Shell'],
    'wood' => ['en' => 'Wood'],
    'woodnode' => ['en' => 'Wood Node'],
    // grip == fiber - mislabeled in csv
    'grip' => ['en' => 'Grip'],
    // ResourceInfo
    //************************************************************************
    // Mob data - index from csv file
    'Mob Name' => ['en' => 'Mob Name'],
    'Aggro Range' => ['en' => 'Aggro Range'],
    'D / P*' => ['en' => 'Dodge / Parry'],
    'Physical' => ['en' => 'Physical'],
    'Magic' => ['en' => 'Magic'],
    'Blunt' => ['en' => 'Blunt'],
    'Pierce' => ['en' => 'Pierce'],
    'Slash' => ['en' => 'Slash'],
    'Acid' => ['en' => 'Acid'],
    'Cold' => ['en' => 'Cold'],
    'Rot' => ['en' => 'Rot'],
    'Poison' => ['en' => 'Poison'],
    'Shockwave' => ['en' => 'Shockwave'],
    'Fire' => ['en' => 'Fire'],
    'Electric' => ['en' => 'Electric'],
    //
    'Move Slow' => ['en' => 'Move Slow'],
    'Attack Slow' => ['en' => 'Attack Slow'],
    'Stun' => ['en' => 'Stun'],
    'Sleep' => ['en' => 'Sleep'],
    'Fear' => ['en' => 'Fear'],
    'Blind' => ['en' => 'Blind'],
    'Root' => ['en' => 'Root'],
    'root' => ['en' => 'Root'],
    'parry' => ['en' => 'Parry'],
    'dodge' => ['en' => 'Dodge'],
    'blunt' => ['en' => 'Blunt'],
    'pierce' => ['en' => 'Pierce'],
    'slash' => ['en' => 'Slash'],
    'blind' => ['en' => 'Blind'],
    'fear' => ['en' => 'Fear'],
    'madness' => ['en' => 'Madness'],
    'poison DoT' => ['en' => 'Poison DoT'],
    //
    'acid' => ['en' => 'Acid'],
    'cold' => ['en' => 'Cold'],
    'rot' => ['en' => 'Rot'],
    'electric' => ['en' => 'Electric'],
    'fire' => ['en' => 'Fire'],
    'shockwave' => ['en' => 'Shockwave'],
    'poison' => ['en' => 'Poison'],
    'sw & ele' => ['en' => 'sw & ele'],
    'cold & root' => ['en' => 'Cold and Root'],
    //
    'Attack / Defense Info' => ['en' => 'Attack / Defense Info'],
    'Damage Type' => ['en' => 'Damage Type'],
    'Physical Resistances' => ['en' => 'Physical Resistances'],
    'Magic Protections' => ['en' => 'Magic Protections'],
    'Affliction Immunities' => ['en' => 'Affliction Immunities'],
    //************************************************************************
    // outposts
    'fyros_outpost_04' => ['en' => 'Malmont Farm'],
    'fyros_outpost_09' => ['en' => 'Hightowers Farm'],
    'fyros_outpost_13' => ['en' => 'West Blackburn Border Post'],
    'fyros_outpost_14' => ['en' => 'Blackburn Trade Post'],
    'fyros_outpost_25' => ['en' => 'Southend Dune Farm'],
    'fyros_outpost_27' => ['en' => 'Woodburn Magic Pole'],
    'fyros_outpost_28' => ['en' => 'Woodburn Stronghold'],
    'tryker_outpost_06' => ['en' => 'Greenvale Trade Post'],
    'tryker_outpost_10' => ['en' => 'Fount Porch Trade Post'],
    'tryker_outpost_16' => ['en' => 'Graveyard Gate Research Centre'],
    'tryker_outpost_22' => ['en' => 'Twintops Workshop'],
    'tryker_outpost_24' => ['en' => 'Windway Workshop'],
    'tryker_outpost_29' => ['en' => 'Loria Stronghold'],
    'tryker_outpost_31' => ['en' => 'Whirling Strongold'],
    'zorai_outpost_02' => ['en' => 'Gu-Qin Workshop'],
    'zorai_outpost_08' => ['en' => 'Qai-Du Workshop'],
    'zorai_outpost_10' => ['en' => 'Sai-Shun Stronghold'],
    'zorai_outpost_15' => ['en' => 'Zo-Kian Ruins Workshop'],
    'zorai_outpost_16' => ['en' => 'Lost Valley Stronghold'],
    'zorai_outpost_22' => ['en' => 'Demon\'s Crossroads Diplomatic Outpost'],
    'zorai_outpost_29' => ['en' => 'Great Outback Workshop'],
    'matis_outpost_03' => ['en' => 'Fearing Fen Farm'],
    'matis_outpost_07' => ['en' => 'Finder\'s Farm'],
    'matis_outpost_15' => ['en' => 'Psykopla Knoll Trading Post'],
    'matis_outpost_17' => ['en' => 'Wooky Workshop'],
    'matis_outpost_24' => ['en' => 'Westgrove Stronghold'],
    'matis_outpost_27' => ['en' => 'Ginti Workshop'],
    'matis_outpost_30' => ['en' => 'Berello Gorge Border Post'],
    // regions
    'region_imperialdunes.place' => ['en' => 'Imperial Dunes'],
    'region_oflovaksoasis.place' => ['en' => 'Oflovak\'s Oasis'],
    'region_frahartowers.place' => ['en' => 'Frahar Towers'],
    'region_thesavagedunes.place' => ['en' => 'Savage Dunes'],
    'region_dunesofexil.place' => ['en' => 'Dunes of Exil'],
    'region_thescorchedcorridor.place' => ['en' => 'Scourched Corridor'],
    'region_majesticgarden.place' => ['en' => 'Majestic Garden'],
    'region_fleetinggarden.place' => ['en' => 'Fleeting Garden'],
    'region_knollofdissent.place' => ['en' => 'Knoll of Dissent'],
    'region_hiddensource.place' => ['en' => 'Hidden Source'],
    'region_upperbog.place' => ['en' => 'Upper Bog'],
    'region_groveofconfusion.place' => ['en' => 'Grove of Confusion'],
    'region_libertylake.place' => ['en' => 'Liberty Lake'],
    'region_windsofmuse.place' => ['en' => 'Winds of Muse'],
    'region_thefount.place' => ['en' => 'Fount'],
    'region_enchantedisle.place' => ['en' => 'Enchanted Isle'],
    'region_bountybeaches.place' => ['en' => 'Bounty Beaches'],
    'region_lagoonsofloria.place' => ['en' => 'Lagoons of Loria'],
    'region_citiesofintuition.place' => ['en' => 'Cities of Intuition'],
    'region_maidengrove.place' => ['en' => 'Maiden Grove'],
    'region_havenofpurity.place' => ['en' => 'Haven of Purity'],
    'region_knotofdementia.place' => ['en' => 'Knot of Dementia'],
    'region_groveofumbra.place' => ['en' => 'Grove of Umbra'],
    'region_thevoid.place' => ['en' => 'Void'],
    //************************************************************************
];

