<?php
/**
 * Translation
 *
 * If translation is not found, then 'en' is tried next.
 *
 * If no english translation found, then "<key>[<lang>]" string is used.
 */
return [
    // index from csv
    'amber' => ['en' => 'Amber'],
    'seed' => ['en' => 'Seed'],
    'fiber' => ['en' => 'Fiber'],
    'bark' => ['en' => 'Bark'],
    'sap' => ['en' => 'Sap'],
    'resin' => ['en' => 'Resin'],
    'oil' => ['en' => 'Oil'],
    'shell' => ['en' => 'Shell'],
    'wood' => ['en' => 'Wood'],
    'woodnode' => ['en' => 'Wood Node'],
    // grip == fiber - mislabeled in csv
    'grip' => ['en' => 'Fiber'],
    // ResourceInfo
    //************************************************************************
    // Mob data - index from csv file
    'Mob Name' => ['en' => 'Mob Name'],
    'Aggro Range' => ['en' => 'Aggro Range'],
    'D / P*' => ['en' => 'Dodge / Parry'],
    'Physical' => ['en' => 'Physical'],
    'Magic' => ['en' => 'Magic'],
    'Blunt' => ['en' => 'Blunt'],
    'Pierce' => ['en' => 'Pierce'],
    'Slash' => ['en' => 'Slash'],
    'Acid' => ['en' => 'Acid'],
    'Cold' => ['en' => 'Cold'],
    'Rot' => ['en' => 'Rot'],
    'Poison' => ['en' => 'Poison'],
    'Shockwave' => ['en' => 'Shockwave'],
    'Fire' => ['en' => 'Fire'],
    'Electric' => ['en' => 'Electric'],
    //
    'Move Slow' => ['en' => 'Move Slow'],
    'Attack Slow' => ['en' => 'Attack Slow'],
    'Stun' => ['en' => 'Stun'],
    'Sleep' => ['en' => 'Sleep'],
    'Fear' => ['en' => 'Fear'],
    'Blind' => ['en' => 'Blind'],
    'Root' => ['en' => 'Root'],
    'root' => ['en' => 'Root'],
    'parry' => ['en' => 'Parry'],
    'dodge' => ['en' => 'Dodge'],
    'blunt' => ['en' => 'Blunt'],
    'pierce' => ['en' => 'Pierce'],
    'slash' => ['en' => 'Slash'],
    'blind' => ['en' => 'Blind'],
    'fear' => ['en' => 'Fear'],
    'madness' => ['en' => 'Madness'],
    'poison DoT' => ['en' => 'Poison DoT'],
    //
    'acid' => ['en' => 'Acid'],
    'cold' => ['en' => 'Cold'],
    'rot' => ['en' => 'Rot'],
    'electric' => ['en' => 'Electric'],
    'fire' => ['en' => 'Fire'],
    'shockwave' => ['en' => 'Shockwave'],
    'poison' => ['en' => 'Poison'],
    'sw & ele' => ['en' => 'sw & ele'],
    'cold & root' => ['en' => 'Cold and Root'],
    //
    'Attack / Defense Info' => ['en' => 'Attack / Defense Info'],
    'Damage Type' => ['en' => 'Damage Type'],
    'Physical Resistances' => ['en' => 'Physical Resistances'],
    'Magic Protections' => ['en' => 'Magic Protections'],
    'Affliction Immunities' => ['en' => 'Affliction Immunities'],
    //************************************************************************
    // outposts
    'fyros_outpost_04' => ['en' => 'Malmont Farm'],
    'fyros_outpost_09' => ['en' => 'Hightowers Farm'],
    'fyros_outpost_13' => ['en' => 'West Blackburn Border Post'],
    'fyros_outpost_14' => ['en' => 'Blackburn Trade Post'],
    'fyros_outpost_25' => ['en' => 'Southend Dune Farm'],
    'fyros_outpost_27' => ['en' => 'Woodburn Magic Pole'],
    'fyros_outpost_28' => ['en' => 'Woodburn Stronghold'],
    'tryker_outpost_06' => ['en' => 'Greenvale Trade Post'],
    'tryker_outpost_10' => ['en' => 'Fount Porch Trade Post'],
    'tryker_outpost_16' => ['en' => 'Graveyard Gate Research Centre'],
    'tryker_outpost_22' => ['en' => 'Twintops Workshop'],
    'tryker_outpost_24' => ['en' => 'Windway Workshop'],
    'tryker_outpost_29' => ['en' => 'Loria Stronghold'],
    'tryker_outpost_31' => ['en' => 'Whirling Strongold'],
    'zorai_outpost_02' => ['en' => 'Gu-Qin Workshop'],
    'zorai_outpost_08' => ['en' => 'Qai-Du Workshop'],
    'zorai_outpost_10' => ['en' => 'Sai-Shun Stronghold'],
    'zorai_outpost_15' => ['en' => 'Zo-Kian Ruins Workshop'],
    'zorai_outpost_16' => ['en' => 'Lost Valley Stronghold'],
    'zorai_outpost_22' => ['en' => 'Demon\'s Crossroads Diplomatic Outpost'],
    'zorai_outpost_29' => ['en' => 'Great Outback Workshop'],
    'matis_outpost_03' => ['en' => 'Fearing Fen Farm'],
    'matis_outpost_07' => ['en' => 'Finder\'s Farm'],
    'matis_outpost_15' => ['en' => 'Psykopla Knoll Trading Post'],
    'matis_outpost_17' => ['en' => 'Wooky Workshop'],
    'matis_outpost_24' => ['en' => 'Westgrove Stronghold'],
    'matis_outpost_27' => ['en' => 'Ginti Workshop'],
    'matis_outpost_30' => ['en' => 'Berello Gorge Border Post'],
    // regions
    'region_imperialdunes.place' => ['en' => 'Imperial Dunes'],
    'region_oflovaksoasis.place' => ['en' => 'Oflovak\'s Oasis'],
    'region_frahartowers.place' => ['en' => 'Frahar Towers'],
    'region_thesavagedunes.place' => ['en' => 'Savage Dunes'],
    'region_dunesofexil.place' => ['en' => 'Dunes of Exil'],
    'region_thescorchedcorridor.place' => ['en' => 'Scourched Corridor'],
    'region_majesticgarden.place' => ['en' => 'Majestic Garden'],
    'region_fleetinggarden.place' => ['en' => 'Fleeting Garden'],
    'region_knollofdissent.place' => ['en' => 'Knoll of Dissent'],
    'region_hiddensource.place' => ['en' => 'Hidden Source'],
    'region_upperbog.place' => ['en' => 'Upper Bog'],
    'region_groveofconfusion.place' => ['en' => 'Grove of Confusion'],
    'region_libertylake.place' => ['en' => 'Liberty Lake'],
    'region_windsofmuse.place' => ['en' => 'Winds of Muse'],
    'region_thefount.place' => ['en' => 'Fount'],
    'region_enchantedisle.place' => ['en' => 'Enchanted Isle'],
    'region_bountybeaches.place' => ['en' => 'Bounty Beaches'],
    'region_lagoonsofloria.place' => ['en' => 'Lagoons of Loria'],
    'region_citiesofintuition.place' => ['en' => 'Cities of Intuition'],
    'region_maidengrove.place' => ['en' => 'Maiden Grove'],
    'region_havenofpurity.place' => ['en' => 'Haven of Purity'],
    'region_knotofdementia.place' => ['en' => 'Knot of Dementia'],
    'region_groveofumbra.place' => ['en' => 'Grove of Umbra'],
    'region_thevoid.place' => ['en' => 'Void'],
    //************************************************************************
    //
    'LightBoots' => ['en' => 'Boots'],
    'LightGloves' => ['en' => 'Gloves'],
    'LightPants' => ['en' => 'Pants'],
    'LightSleeves' => ['en' => 'Sleeves'],
    'LightVest' => ['en' => 'Vest'],
    'MediumBoots' => ['en' => 'Boots'],
    'MediumGloves' => ['en' => 'Gloves'],
    'MediumPants' => ['en' => 'Pants'],
    'MediumSleeves' => ['en' => 'Sleeves'],
    'MediumVest' => ['en' => 'Vest'],
    'HeavyBoots' => ['en' => 'Boots'],
    'HeavyGloves' => ['en' => 'Gloves'],
    'HeavyPants' => ['en' => 'Pants'],
    'HeavySleeves' => ['en' => 'Sleeves'],
    'HeavyVest' => ['en' => 'Vest'],
    'HeavyHelmet' => ['en' => 'Helmet'],
    //
    'TwoHandSword' => ['en' => '2H Sword'],
    'TwoHandAxe' => ['en' => '2H Axe'],
    'TwoHandMace' => ['en' => '2H Mace'],
    'MagicianStaff' => ['en' => 'Magic Amplifier'],
    //
    'Autolauch' => ['en' => 'Autolauncher'],
    'Bowrifle' => ['en' => 'Bowrifle'],
    'Launcher' => ['en' => 'Launcher'],
    'Pistol' => ['en' => 'Pistol'],
    'Bowpistol' => ['en' => 'Bowpistol'],
    'Rifle' => ['en' => 'Rifle'],
    //
    'AutolaunchAmmo' => ['en' => 'Autolauncher'],
    'BowrifleAmmo' => ['en' => 'Bowrifle'],
    'LauncherAmmo' => ['en' => 'Launcher'],
    'PistolAmmo' => ['en' => 'Pistol'],
    'BowpistolAmmo' => ['en' => 'Bowpistol'],
    'RifleAmmo' => ['en' => 'Rifle'],
    //
    'lightarmor' => 'Light Armor',
    'mediumarmor' => 'Medium Armor',
    'heavyarmor' => 'Heavy Armor',
    'shield' => 'Shield',
    'jewels' => 'Jewels',
    'amps' => 'Magic Amplifier',
    '1hmelee' => '1H Melee Weapons',
    '2hmelee' => '2H Melee Weapons',
    '1hrange' => '1H Range Weapons',
    '2hrange' => '2H Range Weapons',
    '1hammo' => '1H Range Weapons Ammo',
    '2hammo' => '2H Range Weapons Ammo',
    //************************************************************************
    'dmg/min' => ['en' => 'Damage / Min.'],
    'mpstat0.uxt' => ['en' => 'Durability'],
    'mpstat1.uxt' => ['en' => 'Lightness (kg)'],
    'mpstat2.uxt' => ['en' => 'Sap Load'],
    'mpstat3.uxt' => ['en' => 'Damage'],
    'mpstat4.uxt' => ['en' => 'Speed (hit/min)'],
    'mpstat5.uxt' => ['en' => 'Range (m)'],
    'mpstat6.uxt' => ['en' => 'Dodge Modifier'],
    'mpstat7.uxt' => ['en' => 'Parry Modifier'],
    'mpstat8.uxt' => ['en' => 'Adversary Dodge Modifier'],
    'mpstat9.uxt' => ['en' => 'Adversary Parry Modifier'],
    'mpstat10.uxt' => ['en' => 'Protection Factor'],
    'mpstat11.uxt' => ['en' => 'Max. Slashing Protection'],
    'mpstat12.uxt' => ['en' => 'Max. Smashing Protection'],
    'mpstat13.uxt' => ['en' => 'Max. Piercing Protection'],
    'mpstat14.uxt' => ['en' => 'Acid Protection'],
    'mpstat15.uxt' => ['en' => 'Cold Protection'],
    'mpstat16.uxt' => ['en' => 'Rot Protection'],
    'mpstat17.uxt' => ['en' => 'Fire Protection'],
    'mpstat18.uxt' => ['en' => 'Shockwave Protection'],
    'mpstat19.uxt' => ['en' => 'Poison Protection'],
    'mpstat20.uxt' => ['en' => 'Electricity Protection'],
    'mpstat21.uxt' => ['en' => 'Desert Resistance'],
    'mpstat22.uxt' => ['en' => 'Forest Resistance'],
    'mpstat23.uxt' => ['en' => 'Lakes Resistance'],
    'mpstat24.uxt' => ['en' => 'Jungle Resistance'],
    'mpstat25.uxt' => ['en' => 'Prime Roots Resistance'],
    'mpstat26.uxt' => ['en' => 'Elemental Cast Speed'],
    'mpstat27.uxt' => ['en' => 'Elemental Power'],
    'mpstat28.uxt' => ['en' => 'Off. Affliction Cast Speed'],
    'mpstat29.uxt' => ['en' => 'Off. Affliction Power'],
    'mpstat30.uxt' => ['en' => 'Def. Affliction Cast Speed'],
    'mpstat31.uxt' => ['en' => 'Def. Affliction Power'],
    'mpstat32.uxt' => ['en' => 'Healing Cast Speed'],
    'mpstat33.uxt' => ['en' => 'Healing Power'],
];

