<?php return array (
  'Durability' =>
  array (
    'Dagger' => '100.0',
    'Sword' => '100.0',
    'Mace' => '100.0',
    'Axe' => '100.0',
    'Spear' => '100.0',
    'Staff' => '100.0',
    'MagicianStaff' => '100.0',
    'TwoHandSword' => '100.0',
    'TwoHandAxe' => '100.0',
    'Pike' => '100.0',
    'TwoHandMace' => '100.0',
    'Autolauch' => '100.0',
    'Bowrifle' => '100.0',
    'Launcher' => '100.0',
    'Pistol' => '100.0',
    'Bowpistol' => '100.0',
    'Rifle' => '100.0',
    'AutolaunchAmmo' => '100.0',
    'BowrifleAmmo' => '100.0',
    'LauncherAmmo' => '100.0',
    'PistolAmmo' => '100.0',
    'BowpistolAmmo' => '100.0',
    'RifleAmmo' => '100.0',
    'Shield' => '100.0',
    'Buckler' => '150.0',
    'LightBoots' => '100.0',
    'LightGloves' => '100.0',
    'LightPants' => '100.0',
    'LightSleeves' => '100.0',
    'LightVest' => '100.0',
    'MediumBoots' => '150.0',
    'MediumGloves' => '150.0',
    'MediumPants' => '150.0',
    'MediumSleeves' => '150.0',
    'MediumVest' => '150.0',
    'HeavyBoots' => '200.0',
    'HeavyGloves' => '200.0',
    'HeavyPants' => '200.0',
    'HeavySleeves' => '200.0',
    'HeavyVest' => '200.0',
    'HeavyHelmet' => '200.0',
    'Anklet' => '100.0',
    'Bracelet' => '100.0',
    'Diadem' => '100.0',
    'Earing' => '100.0',
    'Pendant' => '100.0',
    'Ring' => '100.0',
  ),
  'Weight' =>
  array (
    'Dagger' => '3.5',
    'Sword' => '4.0',
    'Mace' => '4.0',
    'Axe' => '4.0',
    'Spear' => '4.0',
    'Staff' => '1.0',
    'MagicianStaff' => '2.0',
    'TwoHandSword' => '6.0',
    'TwoHandAxe' => '6.0',
    'Pike' => '6.0',
    'TwoHandMace' => '6.0',
    'Pistol' => '1.5',
    'Bowpistol' => '1.5',
    'Rifle' => '2.0',
    'Bowrifle' => '2.0',
    'Autolauch' => '8.0',
    'Launcher' => '8.0',
    'PistolAmmo' => '0.2',
    'BowpistolAmmo' => '0.2',
    'RifleAmmo' => '0.2',
    'BowrifleAmmo' => '0.2',
    'AutolaunchAmmo' => '4.8',
    'LauncherAmmo' => '10.0',
    'Shield' => '3.0',
    'Buckler' => '1.5',
    'LightBoots' => '1.0',
    'LightGloves' => '1.0',
    'LightPants' => '2.5',
    'LightSleeves' => '1.0',
    'LightVest' => '2.5',
    'MediumBoots' => '2.0',
    'MediumGloves' => '2.0',
    'MediumPants' => '5.0',
    'MediumSleeves' => '2.0',
    'MediumVest' => '5.0',
    'HeavyBoots' => '4.0',
    'HeavyGloves' => '4.0',
    'HeavyPants' => '10.0',
    'HeavySleeves' => '4.0',
    'HeavyVest' => '10.0',
    'HeavyHelmet' => '4.0',
    'Anklet' => '0.1',
    'Bracelet' => '0.1',
    'Diadem' => '0.1',
    'Earing' => '0.1',
    'Pendant' => '0.1',
    'Ring' => '0.1',
  ),
  'SapLoad' =>
  array (
    'Dagger' => '0.0',
    'Sword' => '0.0',
    'Mace' => '0.0',
    'Axe' => '0.0',
    'Spear' => '0.0',
    'Staff' => '0.0',
    'MagicianStaff' => '0.0',
    'TwoHandSword' => '0.0',
    'TwoHandAxe' => '0.0',
    'Pike' => '0.0',
    'TwoHandMace' => '0.0',
    'Autolauch' => '0.0',
    'Bowrifle' => '0.0',
    'Launcher' => '0.0',
    'Pistol' => '0.0',
    'Bowpistol' => '0.0',
    'Rifle' => '0.0',
  ),
  'SapLoadMax' =>
  array (
    'Dagger' => '2500.0',
    'Sword' => '2500.0',
    'Mace' => '2500.0',
    'Axe' => '2500.0',
    'Spear' => '2500.0',
    'Staff' => '7000.0',
    'MagicianStaff' => '2500.0',
    'TwoHandSword' => '2500.0',
    'TwoHandAxe' => '2500.0',
    'Pike' => '2500.0',
    'TwoHandMace' => '2500.0',
    'Autolauch' => '2500.0',
    'Bowrifle' => '2500.0',
    'Launcher' => '2500.0',
    'Pistol' => '2500.0',
    'Bowpistol' => '2500.0',
    'Rifle' => '2500.0',
  ),
  'Dmg' =>
  array (
    'Dagger' => '0.250',
    'Staff' => '0.250',
    'Sword' => '0.666',
    'Mace' => '0.800',
    'Axe' => '0.800',
    'Spear' => '0.550',
    'TwoHandSword' => '1.000',
    'TwoHandAxe' => '1.200',
    'Pike' => '0.800',
    'TwoHandMace' => '1.200',
    'MagicianStaff' => '0.350',
    'Pistol' => '0.0',
    'Bowpistol' => '0.0',
    'Rifle' => '0.0',
    'Bowrifle' => '0.0',
    'Autolauch' => '0.0',
    'Launcher' => '0.0',
    'PistolAmmo' => '0.625',
    'BowpistolAmmo' => '0.625',
    'RifleAmmo' => '0.833',
    'BowrifleAmmo' => '0.833',
    'AutolaunchAmmo' => '2.0',
    'LauncherAmmo' => '3.0',
  ),
  'DmgMax' =>
  array (
    'Dagger' => '0.500',
    'Staff' => '0.500',
    'Sword' => '1.333',
    'Mace' => '1.600',
    'Axe' => '1.600',
    'Spear' => '1.100',
    'TwoHandSword' => '2.000',
    'TwoHandAxe' => '2.400',
    'Pike' => '1.600',
    'TwoHandMace' => '2.400',
    'MagicianStaff' => '0.350',
    'Autolauch' => '0.0',
    'Bowrifle' => '0.0',
    'Launcher' => '0.0',
    'Pistol' => '0.0',
    'Bowpistol' => '0.0',
    'Rifle' => '0.0',
    'PistolAmmo' => '1.25',
    'BowpistolAmmo' => '1.25',
    'RifleAmmo' => '1.666',
    'BowrifleAmmo' => '1.666',
    'AutolaunchAmmo' => '4.0',
    'LauncherAmmo' => '6.0',
  ),
  'HitRate' =>
  array (
    'Dagger' => '5.0',
    'Staff' => '3.333',
    'Sword' => '3.333',
    'Mace' => '3.030',
    'Axe' => '3.030',
    'Spear' => '3.700',
    'TwoHandSword' => '2.500',
    'TwoHandAxe' => '2.272',
    'Pike' => '2.777',
    'TwoHandMace' => '2.272',
    'MagicianStaff' => '2.5',
    'Pistol' => '2.5',
    'Bowpistol' => '2.5',
    'Rifle' => '2.0',
    'Bowrifle' => '2.0',
    'Autolauch' => '1.0',
    'Launcher' => '1.0',
    'AutolaunchAmmo' => '0.0',
    'BowrifleAmmo' => '0.0',
    'LauncherAmmo' => '0.0',
    'PistolAmmo' => '0.0',
    'BowpistolAmmo' => '0.0',
    'RifleAmmo' => '0.0',
  ),
  'HitRateMax' =>
  array (
    'Dagger' => '10.0',
    'Staff' => '6.666',
    'Sword' => '6.666',
    'Mace' => '6.060',
    'Axe' => '6.060',
    'Spear' => '7.400',
    'TwoHandSword' => '5.0',
    'TwoHandAxe' => '4.545',
    'Pike' => '5.555',
    'TwoHandMace' => '4.545',
    'MagicianStaff' => '2.5',
    'Pistol' => '5.0',
    'Bowpistol' => '5.0',
    'Rifle' => '4.0',
    'Bowrifle' => '4.0',
    'Autolauch' => '2.0',
    'Launcher' => '2.0',
    'AutolaunchAmmo' => '0.0',
    'BowrifleAmmo' => '0.0',
    'LauncherAmmo' => '0.0',
    'PistolAmmo' => '0.0',
    'BowpistolAmmo' => '0.0',
    'RifleAmmo' => '0.0',
  ),
  'Range' =>
  array (
    'Autolauch' => '25000.0',
    'Bowrifle' => '20000.0',
    'Launcher' => '30000.0',
    'Pistol' => '15000.0',
    'Bowpistol' => '15000.0',
    'Rifle' => '20000.0',
    'AutolaunchAmmo' => '0.0',
    'BowrifleAmmo' => '0.0',
    'LauncherAmmo' => '0.0',
    'PistolAmmo' => '0.0',
    'BowpistolAmmo' => '0.0',
    'RifleAmmo' => '0.0',
  ),
  'DodgeMinModifier' =>
  array (
    'Dagger' => '0.0',
    'Sword' => '-10.0',
    'Mace' => '-10.0',
    'Axe' => '-10.0',
    'Spear' => '-5.0',
    'Staff' => '-10.0',
    'TwoHandSword' => '-20.0',
    'TwoHandAxe' => '-20.0',
    'Pike' => '-20.0',
    'TwoHandMace' => '-20.0',
    'MagicianStaff' => '0.0',
    'Autolauch' => '-15.0',
    'Bowrifle' => '-10.0',
    'Launcher' => '-20.0',
    'Pistol' => '0.0',
    'Bowpistol' => '-5.0',
    'Rifle' => '-20.0',
    'Shield' => '-10.0',
    'Buckler' => '0.0',
    'LightBoots' => '1.0',
    'LightGloves' => '1.0',
    'LightPants' => '1.0',
    'LightSleeves' => '1.0',
    'LightVest' => '1.0',
    'MediumBoots' => '-2.0',
    'MediumGloves' => '-2.0',
    'MediumPants' => '-2.0',
    'MediumSleeves' => '-2.0',
    'MediumVest' => '-2.0',
    'HeavyBoots' => '-4.0',
    'HeavyGloves' => '-4.0',
    'HeavyPants' => '-4.0',
    'HeavySleeves' => '-4.0',
    'HeavyVest' => '-4.0',
    'HeavyHelmet' => '-4.0',
  ),
  'DodgeMaxModifier' =>
  array (
    'Dagger' => '20.0',
    'Sword' => '10.0',
    'Mace' => '10.0',
    'Axe' => '10.0',
    'Spear' => '15.0',
    'Staff' => '10.0',
    'TwoHandSword' => '0.0',
    'TwoHandAxe' => '0.0',
    'Pike' => '0.0',
    'TwoHandMace' => '0.0',
    'MagicianStaff' => '0.0',
    'Autolauch' => '5.0',
    'Bowrifle' => '10.0',
    'Launcher' => '0.0',
    'Pistol' => '20.0',
    'Bowpistol' => '15.0',
    'Rifle' => '0.0',
    'Shield' => '0.0',
    'Buckler' => '20.0',
    'LightBoots' => '2.0',
    'LightGloves' => '2.0',
    'LightPants' => '2.0',
    'LightSleeves' => '2.0',
    'LightVest' => '2.0',
    'MediumBoots' => '1.0',
    'MediumGloves' => '1.0',
    'MediumPants' => '1.0',
    'MediumSleeves' => '1.0',
    'MediumVest' => '1.0',
    'HeavyBoots' => '0.0',
    'HeavyGloves' => '0.0',
    'HeavyPants' => '0.0',
    'HeavySleeves' => '0.0',
    'HeavyVest' => '0.0',
    'HeavyHelmet' => '0.0',
  ),
  'ParryMinModifier' =>
  array (
    'Dagger' => '-20.0',
    'Sword' => '-10.0',
    'Mace' => '-15.0',
    'Axe' => '-15.0',
    'Spear' => '-20.0',
    'Staff' => '0.0',
    'TwoHandSword' => '0.0',
    'TwoHandAxe' => '-10.0',
    'Pike' => '-10.0',
    'TwoHandMace' => '-10.0',
    'MagicianStaff' => '0.0',
    'Autolauch' => '0.0',
    'Bowrifle' => '-10.0',
    'Launcher' => '0.0',
    'Pistol' => '-20.0',
    'Bowpistol' => '-5.0',
    'Rifle' => '0.0',
    'Shield' => '10.0',
    'Buckler' => '0.0',
    'LightBoots' => '-1.0',
    'LightGloves' => '-1.0',
    'LightPants' => '-1.0',
    'LightSleeves' => '-1.0',
    'LightVest' => '-1.0',
    'MediumBoots' => '-1.0',
    'MediumGloves' => '-1.0',
    'MediumPants' => '-1.0',
    'MediumSleeves' => '-1.0',
    'MediumVest' => '-1.0',
    'HeavyBoots' => '-1.0',
    'HeavyGloves' => '-1.0',
    'HeavyPants' => '-1.0',
    'HeavySleeves' => '-1.0',
    'HeavyVest' => '-1.0',
    'HeavyHelmet' => '-1.0',
  ),
  'ParryMaxModifier' =>
  array (
    'Dagger' => '0.0',
    'Sword' => '10.0',
    'Mace' => '5.0',
    'Axe' => '5.0',
    'Spear' => '0.0',
    'Staff' => '20.0',
    'TwoHandSword' => '20.0',
    'TwoHandAxe' => '10.0',
    'Pike' => '10.0',
    'TwoHandMace' => '10.0',
    'MagicianStaff' => '0.0',
    'Autolauch' => '20.0',
    'Bowrifle' => '10.0',
    'Launcher' => '20.0',
    'Pistol' => '0.0',
    'Bowpistol' => '15.0',
    'Rifle' => '20.0',
    'Shield' => '30.0',
    'Buckler' => '20.0',
    'LightBoots' => '1.0',
    'LightGloves' => '1.0',
    'LightPants' => '1.0',
    'LightSleeves' => '1.0',
    'LightVest' => '1.0',
    'MediumBoots' => '2.0',
    'MediumGloves' => '2.0',
    'MediumPants' => '2.0',
    'MediumSleeves' => '2.0',
    'MediumVest' => '2.0',
    'HeavyBoots' => '3.0',
    'HeavyGloves' => '3.0',
    'HeavyPants' => '3.0',
    'HeavySleeves' => '3.0',
    'HeavyVest' => '3.0',
    'HeavyHelmet' => '3.0',
  ),
  'AdversaryDodgeMinModifier' =>
  array (
    'Dagger' => '0.0',
    'Sword' => '5.0',
    'Mace' => '5.0',
    'Axe' => '5.0',
    'Spear' => '15.0',
    'Staff' => '0.0',
    'TwoHandSword' => '30.0',
    'TwoHandAxe' => '30.0',
    'Pike' => '30.0',
    'TwoHandMace' => '30.0',
    'MagicianStaff' => '0.0',
    'Autolauch' => '30.0',
    'Bowrifle' => '0.0',
    'Launcher' => '30.0',
    'Pistol' => '0.0',
    'Bowpistol' => '0.0',
    'Rifle' => '0.0',
  ),
  'AdversaryDodgeMaxModifier' =>
  array (
    'Dagger' => '-20.0',
    'Sword' => '-15.0',
    'Mace' => '-15.0',
    'Axe' => '-15.0',
    'Spear' => '-5.0',
    'Staff' => '-20.0',
    'TwoHandSword' => '15.0',
    'TwoHandAxe' => '15.0',
    'Pike' => '15.0',
    'TwoHandMace' => '15.0',
    'MagicianStaff' => '0.0',
    'Autolauch' => '15.0',
    'Bowrifle' => '-20.0',
    'Launcher' => '20.0',
    'Pistol' => '-15.0',
    'Bowpistol' => '-15.0',
    'Rifle' => '-20.0',
  ),
  'AdversaryParryMinModifier' =>
  array (
    'Dagger' => '20.0',
    'Sword' => '10.0',
    'Mace' => '15.0',
    'Axe' => '15.0',
    'Spear' => '5.0',
    'Staff' => '-5.0',
    'TwoHandSword' => '0.0',
    'TwoHandAxe' => '0.0',
    'Pike' => '0.0',
    'TwoHandMace' => '0.0',
    'MagicianStaff' => '0.0',
    'Autolauch' => '10.0',
    'Bowrifle' => '0.0',
    'Launcher' => '20.0',
    'Pistol' => '0.0',
    'Bowpistol' => '0.0',
    'Rifle' => '0.0',
  ),
  'AdversaryParryMaxModifier' =>
  array (
    'Dagger' => '0.0',
    'Sword' => '-10.0',
    'Mace' => '-5.0',
    'Axe' => '-5.0',
    'Spear' => '-5.0',
    'Staff' => '-15.0',
    'TwoHandSword' => '-30.0',
    'TwoHandAxe' => '-20.0',
    'Pike' => '-20.0',
    'TwoHandMace' => '-20.0',
    'MagicianStaff' => '0.0',
    'Autolauch' => '-10.0',
    'Bowrifle' => '-20.0',
    'Launcher' => '0.0',
    'Pistol' => '-20.0',
    'Bowpistol' => '-20.0',
    'Rifle' => '-20.0',
  ),
  'ElementalCastingTimeFactor' =>
  array (
    'MagicianStaff' => '0.2',
  ),
  'ElementalCastingTimeFactorMax' =>
  array (
    'MagicianStaff' => '1.0',
  ),
  'ElementalPowerFactor' =>
  array (
    'MagicianStaff' => '0.2',
  ),
  'ElementalPowerFactorMax' =>
  array (
    'MagicianStaff' => '1.0',
  ),
  'OffensiveAfflictionCastingTimeFactor' =>
  array (
    'MagicianStaff' => '0.2',
  ),
  'OffensiveAfflictionCastingTimeFactorMax' =>
  array (
    'MagicianStaff' => '1.0',
  ),
  'OffensiveAfflictionPowerFactor' =>
  array (
    'MagicianStaff' => '0.2',
  ),
  'OffensiveAfflictionPowerFactorMax' =>
  array (
    'MagicianStaff' => '1.0',
  ),
  'HealCastingTimeFactor' =>
  array (
    'MagicianStaff' => '0.2',
  ),
  'HealCastingTimeFactorMax' =>
  array (
    'MagicianStaff' => '1.0',
  ),
  'HealPowerFactor' =>
  array (
    'MagicianStaff' => '0.2',
  ),
  'HealPowerFactorMax' =>
  array (
    'MagicianStaff' => '1.0',
  ),
  'DefensiveAfflictionCastingTimeFactor' =>
  array (
    'MagicianStaff' => '0.2',
  ),
  'DefensiveAfflictionCastingTimeFactorMax' =>
  array (
    'MagicianStaff' => '1.0',
  ),
  'DefensiveAfflictionPowerFactor' =>
  array (
    'MagicianStaff' => '0.2',
  ),
  'DefensiveAfflictionPowerFactorMax' =>
  array (
    'MagicianStaff' => '1.0',
  ),
  'ProtectionFactor' =>
  array (
    'Buckler' => '0.08',
    'Shield' => '0.16',
    'LightBoots' => '0.05',
    'LightGloves' => '0.05',
    'LightPants' => '0.05',
    'LightSleeves' => '0.05',
    'LightVest' => '0.05',
    'MediumBoots' => '0.20',
    'MediumGloves' => '0.20',
    'MediumPants' => '0.20',
    'MediumSleeves' => '0.20',
    'MediumVest' => '0.20',
    'HeavyBoots' => '0.40',
    'HeavyGloves' => '0.40',
    'HeavyPants' => '0.40',
    'HeavySleeves' => '0.40',
    'HeavyVest' => '0.40',
    'HeavyHelmet' => '0.40',
  ),
  'ProtectionFactorMax' =>
  array (
    'Buckler' => '0.12',
    'Shield' => '0.24',
    'LightBoots' => '0.25',
    'LightGloves' => '0.25',
    'LightPants' => '0.25',
    'LightSleeves' => '0.25',
    'LightVest' => '0.25',
    'MediumBoots' => '0.40',
    'MediumGloves' => '0.40',
    'MediumPants' => '0.40',
    'MediumSleeves' => '0.40',
    'MediumVest' => '0.40',
    'HeavyBoots' => '0.60',
    'HeavyGloves' => '0.60',
    'HeavyPants' => '0.60',
    'HeavySleeves' => '0.60',
    'HeavyVest' => '0.60',
    'HeavyHelmet' => '0.60',
  ),
  'MaxSlashingProtection' =>
  array (
    'Buckler' => '0.24',
    'Shield' => '0.48',
    'LightBoots' => '0.56',
    'LightGloves' => '0.56',
    'LightPants' => '0.56',
    'LightSleeves' => '0.56',
    'LightVest' => '0.56',
    'MediumBoots' => '0.89',
    'MediumGloves' => '0.89',
    'MediumPants' => '0.89',
    'MediumSleeves' => '0.89',
    'MediumVest' => '0.89',
    'HeavyBoots' => '1.33',
    'HeavyGloves' => '1.33',
    'HeavyPants' => '1.33',
    'HeavySleeves' => '1.33',
    'HeavyVest' => '1.33',
    'HeavyHelmet' => '1.33',
  ),
  'MaxBluntProtection' =>
  array (
    'Buckler' => '0.24',
    'Shield' => '0.48',
    'LightBoots' => '0.56',
    'LightGloves' => '0.56',
    'LightPants' => '0.56',
    'LightSleeves' => '0.56',
    'LightVest' => '0.56',
    'MediumBoots' => '0.89',
    'MediumGloves' => '0.89',
    'MediumPants' => '0.89',
    'MediumSleeves' => '0.89',
    'MediumVest' => '0.89',
    'HeavyBoots' => '1.33',
    'HeavyGloves' => '1.33',
    'HeavyPants' => '1.33',
    'HeavySleeves' => '1.33',
    'HeavyVest' => '1.33',
    'HeavyHelmet' => '1.33',
  ),
  'MaxPiercingProtection' =>
  array (
    'Buckler' => '0.24',
    'Shield' => '0.48',
    'LightBoots' => '0.56',
    'LightGloves' => '0.56',
    'LightPants' => '0.56',
    'LightSleeves' => '0.56',
    'LightVest' => '0.56',
    'MediumBoots' => '0.89',
    'MediumGloves' => '0.89',
    'MediumPants' => '0.89',
    'MediumSleeves' => '0.89',
    'MediumVest' => '0.89',
    'HeavyBoots' => '1.33',
    'HeavyGloves' => '1.33',
    'HeavyPants' => '1.33',
    'HeavySleeves' => '1.33',
    'HeavyVest' => '1.33',
    'HeavyHelmet' => '1.33',
  ),
  'AcidJewelProtection' =>
  array (
    'Jewel' => '0.08001',
  ),
  'ColdJewelProtection' =>
  array (
    'Jewel' => '0.08001',
  ),
  'FireJewelProtection' =>
  array (
    'Jewel' => '0.08001',
  ),
  'RotJewelProtection' =>
  array (
    'Jewel' => '0.08001',
  ),
  'ShockWaveJewelProtection' =>
  array (
    'Jewel' => '0.08001',
  ),
  'PoisonJewelProtection' =>
  array (
    'Jewel' => '0.08001',
  ),
  'ElectricityJewelProtection' =>
  array (
    'Jewel' => '0.08001',
  ),
  'DesertResistance' =>
  array (
    'Jewel' => '8',
  ),
  'ForestResistance' =>
  array (
    'Jewel' => '8',
  ),
  'LacustreResistance' =>
  array (
    'Jewel' => '8',
  ),
  'JungleResistance' =>
  array (
    'Jewel' => '8',
  ),
  'PrimaryRootResistance' =>
  array (
    'Jewel' => '8',
  ),
);
